CREATE  VIEW [BASELINE].[ABONNOMENTER_PR_MND_V]
--INDEHOLDER ALLE MOBILABONNOMENTER I EN GIVEN MÅNED SIDEN 1. JANUAR 2019
--UNION GENNEMFØRES, DA AKTUELLE ABONOMENTER STÅR I ADMIN.MOBIL_ABN. HVIS ET ABONNOMENT OPHØRER FLYTTES RÆKKEN TIL ADMIN.MOBIL_ABN_OLD
AS
SELECT A.*, DATOBLOK.DATE_ID FROM BASELINE.ABONNOMENT_V A
JOIN 
	(
	SELECT DISTINCT(LASTDAYOFMONTH) AS DATE_ID
	FROM REPORTING.DIM_DATO
	WHERE YEAR(DATE) BETWEEN 2019 AND YEAR(GETDATE())
	) DATOBLOK ON DATOBLOK.DATE_ID BETWEEN A.STARTDATE AND ENDDATE
;

GO

