ALTER VIEW BASELINE.TURNOVER_BUDGET_V
--DATA FOR THIS CURRENT FISCAL YEAR
--IS POPULATED BY THE PROCEURE [navision].[CREATE_TABLE_TURNOVER_BUDGET]
--THE VIEWS IS LATER USED BY THE PROCEDURE REPORTING.MERGE_TURNOVER AND POWER BI
AS
SELECT 
B.[DATE_ID],
D.[FISCALYEARTEXT],
B.[BUDGET] AS BUDGET_MONTH,
B.[BUDGET_RUNNING_SUM]
FROM [NAVISION].[TURNOVER_BUDGET] B
INNER JOIN BASELINE.DIM_DATO D ON B.DATE_ID=D.[DATE];
