ALTER  VIEW BASELINE.DIM_RESSOURCEGROUP_V
	AS
	
	SELECT 
	[NO_] AS RESSOURCEGROUP_ID,
	[NAME] AS RESSOUCEGROUP_NAVN,
	[TYPE] AS RESSOURCEGROUP_TYPE,
	[BASE UNIT OF MEASURE] AS BASISENHED,
	[UNIT PRICE] AS ENHEDSPRIS,
	[GEN_ PROD_ POSTING GROUP] AS PRODUKTBOGFØRINGSGRUPPE,
	CASE 
	WHEN [NO_] NOT BETWEEN 31 AND 33 THEN [GEN_ PROD_ POSTING GROUP] 
	WHEN [NO_] BETWEEN 31 AND 33 THEN 'SIP'
	ELSE [GEN_ PROD_ POSTING GROUP] END AS PRODUKTBOGFØRINGSGRUPPE_RED
	FROM [NAVISION].[UNI-TEL_AS_RESOURCE];

GO

