ALTER VIEW [BASELINE].[FACT_OMSÆTNING_V]
AS
(
SELECT 
N.[Line No_] AS LINJE_NR,
CAST (N.[Posting Date] AS DATE) AS BOGFØRINGSDATO, 
DATEADD (D, 14, CAST (N.[Posting Date] AS DATE)) AS BETALINGSFRIST,
N.[Document No_] AS FAKTURA_NR,
N.DESCRIPTION AS BESKRIVELSE,
N.[Sell-to Customer No_] as KUNDE_ID,
N.[NO_ ] AS RESSOURCEGROUP_ID,
CAST (N.Quantity AS DECIMAL (38,20)) AS ANTAL_ENHEDER, 
CAST (N.[Unit Price] AS DECIMAL (38,20)) AS ENHEDSPRIS,
CAST (N.Quantity AS DECIMAL (38,20)) * CAST (N.[Unit Price] AS DECIMAL (38,20)) AS BELØB_EKSKL_MOMS,
n.[Line Discount _] as LINJE_RABAT,
n.[Line Discount Amount] as LINE_RABAT_BELØB,
LOAD_DATO 
FROM navision.[Uni-tel_AS_Sales_Invoice_Line] N
)
