CREATE VIEW [BASELINE].[FACT_FAKTURERINGSGRUNDLAG_V]
AS
(
SELECT 
N.[Entry No_] AS RÆKKE_ID,
--INVNUMMER er IKKE et unikt fakturanummer antager værdien 'N' ved skift i kunde ver måned. Populeres af et PERL script. Medtages for at kunne backtrace data 
N.INVNUMBER AS FAKTURA_LOBENUMMER, 
CAST (N.[Posted Sales Inv No_] AS bigint) AS FAKTURA_NR, 
--BOGFØRINGSDATO (TRANSDATE) OG BETALINGSFRIST (DUEDATE) ER TEKSTSTRENGE I KILDEN OG IKKE ENS FOR HELE FAKTUREN. 
--DERFOR ÆNDRES FORMATET OG EN MAX DATE AFVIKLES FOR HVER "VINDUE" BESTÅENDE AF FAKTURA_NR
max(CONVERT (DATE, (SUBSTRING(TRANSDATE,1,6)+'20'+RIGHT(TRANSDATE,2)),103)) over (partition by CAST (N.[Posted Sales Inv No_] AS bigint)) as BOGFØRINGSDATO,
max(CONVERT (DATE, (SUBSTRING(DUEDATE,1,6)+'20'+RIGHT(DUEDATE,2)),103)) over (partition by CAST (N.[Posted Sales Inv No_] AS bigint)) as BETALINGSFRIST,
N.CUSTOMERNUMBER AS KUNDE_ID, 
N.DESCRIPTION AS BESKRIVELSE, 
N.PARTNUMBER AS RESSOURCEGROUP_ID,
N.[Line Discount _] as LINJE_RABAT,
CAST (N.Quantity AS DECIMAL (38,20)) AS ANTAL_ENHEDER, 
CAST (N.[SELL PRICE] AS DECIMAL (38,20)) AS ENHEDSPRIS,
CAST (N.Quantity AS DECIMAL (38,20)) * CAST (N.[SELL PRICE] AS DECIMAL (38,20)) AS BELØB_EKSKL_MOMS,
load_dato as LOAD_DATO

--GRUNDLAG FOR FAKTURERING DVS. IKKE BOGFØRTE LINJER
FROM NAVISION.[UNI-TEL_AS_INVOICE_LINE] N

--" ADSKILLERE" SKABT AF PEARL SCRIPT FJERNES
WHERE 
N.INVNUMBER <>'N'
AND 
DESCRIPTION <>'----------------------'
--AND 
--CAST (N.[Posted Sales Inv No_] AS bigint)=480360
);

GO

