ALTER VIEW [BASELINE].[FACT_MOBIL_DATA_V]
AS
(
SELECT D.*, K.KUNDE_ID, P.PRODUCT_ID FROM 
(
	--DATA FORBRUG
	SELECT F.LAST_DAY_OF_MONTH_DT AS DATE_ID, F.ABN_ID AS ABONNEMENT_ID, 
	
	--DATATRAFIK INDEBÆRER BÅDE UP- OG DOWNLOAD
	SUM (CAST (F.VOLUME_GB AS DECIMAL (36,4))) AS DATATRAFIK_TOTAL,
	SUM (CASE WHEN F.INVOICEGROUP_ID=20 THEN CAST (F.VOLUME_GB AS DECIMAL (36,4)) ELSE NULL END) AS DATATRAFIK_EU,
	SUM (CASE WHEN F.INVOICEGROUP_ID!=20 THEN CAST (F.VOLUME_GB AS DECIMAL (36,4)) ELSE NULL END) AS DATATRAFIK_REST,

	--UNITELS OMKOSTNINGER HOS LEVERANDØR
	SUM (CAST (F.COST AS DECIMAL (34,2))) AS COST_TOTAL,
	SUM (CASE WHEN F.INVOICEGROUP_ID=20 THEN CAST (F.COST AS DECIMAL (34,2)) ELSE NULL END) AS COST_EU,
	SUM (CASE WHEN F.INVOICEGROUP_ID!=20 THEN CAST (F.COST AS DECIMAL (34,2)) ELSE NULL END) AS COST_REST,

	--TILKØBTE DATAPAKKER 
	SUM(D.DATATILKOB2) as ANTAL_2GB_PK, 
	SUM(D.DATATILKOB10) AS ANTAL_10GB_PK, 
	SUM(D.DATATILKOB50) AS ANTAL_50GB_PK

	FROM RADIUS.MOB_DATA_SUMMARIZED F
	LEFT JOIN BASELINE.MOBIL_EXTRA_DATA_PIVOT D ON F.ABN_ID=D.ABONNEMENT_ID AND F.LAST_DAY_OF_MONTH_DT=D.DATE_ID
	GROUP BY F.LAST_DAY_OF_MONTH_DT, F.ABN_ID
) D
LEFT JOIN REPORTING.DIM_MOBIL_ABONNEMENT A ON D.ABONNEMENT_ID=A.ABONNEMENT_ID
	LEFT JOIN REPORTING.DIM_KUNDE K ON A.CUST=K.KUNDE_ID
	LEFT JOIN REPORTING.DIM_PRODUKT P ON A.ABN=P.ABN_ID
);
GO


