/*Forbrænder til REPORTING.FACT_MOBIL_OPKALD*/
CREATE VIEW [BASELINE].[FACT_MOBIL_OPKALD_V]
AS
SELECT 
ANTAL_UDGAAENDE_OPKALD,
DUR/(60*60) AS VARIGHED_TIMER,
PRICE AS PRIS,
COST AS OMKOSTNING,
INVOICEGROUP AS INVOICEGROUP_ID,
MOB_CUST AS ABONNEMENT_ID,
LAST_DAY_OF_MONTH_DT AS DATE_ID,
P.PRODUCT_ID,
K.KUNDE_ID,
LOAD_DATO AS LOAD_DATE

FROM RADIUS.MOB_CDR_SUMMARIZED S
LEFT JOIN REPORTING.DIM_ABONNEMENT A ON S.MOB_CUST=A.ABONNEMENT_ID
LEFT JOIN REPORTING.DIM_KUNDE K ON A.CUST=K.KUNDE_ID
LEFT JOIN REPORTING.DIM_PRODUKT P ON A.ABN=P.ABN_ID

GO

