CREATE VIEW [BASELINE].[INVOICEGROUP_V]
AS
(
SELECT A.ID AS INVOICEGROUP_ID, A.GROUPNAME AS INVOICEGROUP_NAME, A.SYSTEM, A.DATA, A.EVENT, CAST (A.LOAD_DATO AS DATE) AS LOAD_DATO
FROM RATING.INVOICE_GROUP A
);

GO

