CREATE VIEW [BASELINE].[PRODUKT_V]
AS
/*Udtrykket er et resultatet af grimme kildedata bestående af 3 hovedtabeller der hver udtrykker produkter og der hver har sin egen grupperingstabel. 
Der er dubletter i de tre hovedtabeller udtrykkende de samme produkt. 
Der er anført produktpriser både rating.mob_abn og rating.mob_products 

Udtrykket herunder giver et samlet overblik over alle produkter med abnname som unik forretningsnøgle. 
Rådata kan joines på den source_id, som rådata indeholder - henholdsvis abn_id, product_id og sip_id
*/
SELECT 
--UNIK BUSINESS KEY
U.ABNNAME, 
--FROM RATING.PRODUCTS AND RATING.PRODUCT_CATEGORIES
P.ID AS PRODUCT_ID, P.NAME AS PRODUCT_NAME, P.ONETIME_PRICE AS PRODUCT_ONETIME_PRICE, P.ONGOING_PRICE AS PRODUCT_ONGOING_PRICE, PC.DESCRIPTION AS PRODUCT_GROUP,
--FROM RATING.MOB_ABN AND RATING.MOB_ABN_GROUP
A.ID AS ABN_ID, A.ABNNAME AS ABN_NAME, A.PRIS AS ABN_PRIS, AG.DESCRIPTION AS ABN_GROUP,
--FROM RATING.SIP_ABN AND SIP_ABN_GROUP
S.ID AS SIP_ID, S.ABNNAME AS SIP_NAME, SG.DESCRIPTION AS SIP_GROUP
FROM 
	(
	SELECT LOWER(NAME) AS ABNNAME
	FROM RATING.PRODUCTS
	UNION 
	SELECT LOWER(ABNNAME) AS ABNNAME
	FROM RATING.MOB_ABN
	UNION 
	SELECT LOWER(ABNNAME) AS ABNNAME
	FROM RATING.SIP_ABN
	) U
LEFT JOIN RATING.PRODUCTS P ON LOWER(U.ABNNAME)=LOWER(P.NAME)
LEFT JOIN RATING.PRODUCT_CATEGORIES PC ON P.PRODUCT_CATEGORY=PC.ID

LEFT JOIN RATING.MOB_ABN A ON LOWER(U.ABNNAME)=LOWER(A.ABNNAME)
LEFT JOIN RATING.MOB_ABN_GROUP AG ON A.ABNGROUP=AG.ID

LEFT JOIN RATING.SIP_ABN S ON LOWER(U.ABNNAME)=LOWER(S.ABNNAME)
LEFT JOIN RATING.SIP_ABN_GROUP SG ON S.ABNGROUP=SG.ID;

GO

