

CREATE VIEW [BASELINE].[TRUNK_V]
AS
(
SELECT USERNAME, CUST, CAPACITY, SIPPLATFORM, CREATED, ENDDATE, TRUNKTYPE,
CASE 
	WHEN GETDATE() BETWEEN CREATED AND ENDDATE THEN 1 
	WHEN ENDDATE IS NULL  THEN 1 
	ELSE 0
END AS AKTIV,

CASE 
	WHEN TRUNKTYPE = 1 THEN 'NORMAL TAKSERING' 
	WHEN TRUNKTYPE = 0 THEN 'FLATRATE' 
	ELSE NULL
END AS TRUNKTYPE_NAVN,

CASE 
	WHEN SIPPLATFORM IN (1,3) THEN 'ONE CONNECT' 
	WHEN SIPPLATFORM IN (4) THEN 'TEAMS OG SKYPE FOR BUSINESS' 
	ELSE NULL
END AS SIPPLATFORM_NAVN, 
LOAD_DATO

FROM ADMIN.TRUNK T
)
;

GO

