
ALTER VIEW REPORTING.TURNOVER_TOTAL_V
--AGGREGATES REPORTING.FACT_OMSÆTNING UP TO TOTAL (UNI-TEL A/S) LEVEL
--USED BY REPORTING.MERGE_TURNOVER_TOTAL AND POWER BI
AS
SELECT A.DATE_ID, A.FISCALYEARTEXT, A.TURNOVER_MONTH,
SUM(TURNOVER_MONTH) OVER (PARTITION BY A.FISCALYEARTEXT ORDER BY DATE_ID ASC) AS TURNOVER_RUNNING_SUM
FROM 
(
SELECT 
SUM(F.BELØB_EKSKL_MOMS) AS TURNOVER_MONTH,
D.[DATE] AS DATE_ID, 
D.FISCALYEARTEXT
FROM REPORTING.FACT_OMSÆTNING F
LEFT JOIN REPORTING.DIM_DATO D ON (F.DATE_ID=D.[DATE])
GROUP BY D.[DATE], D.FISCALYEARTEXT
) A;
