CREATE TABLE [REPORTING].[DIM_KPI](
	[KPI_ID] [int] IDENTITY(1,1) NOT NULL,
	[KPI_NAVN] [varchar](256) NOT NULL,
	[GRUPPERING_NAVN] [varchar](256) NULL,
	[ALTERNATIVT_KPI_NAVN] [nchar](10) NULL,
	[INFO_TEKST] [varchar](2048) NULL,
	[DATAGRUNDLAG] [varchar](2048) NULL,
	[AKTIV] [tinyint] NULL,
	[ENHED] [varchar](256) NULL,
	[SORTERING] [tinyint] NULL,
 CONSTRAINT [PK_DIM_KPI] PRIMARY KEY CLUSTERED 
(
	[KPI_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [DIM_KPI_KPI_NAVN_UK] UNIQUE NONCLUSTERED 
(
	[KPI_NAVN] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


