CREATE TABLE [REPORTING].[DIM_OPERATOR] (
    [OPERATOR_ID]   BIGINT         NOT NULL,
    [OPERATOR_NAVN] NVARCHAR (100) NULL,
    [LOAD_DATO]     DATE           NULL,
    CONSTRAINT [PK_DimOperatør] PRIMARY KEY CLUSTERED ([OPERATOR_ID] ASC)
);


GO

