CREATE TABLE [REPORTING].[DIM_RESSOURCEGROUP] (
    [RESSOURCEGROUP_ID]       INT           NOT NULL,
    [RESSOURCEGROUP_NAVN]     NVARCHAR (50) NOT NULL,
    [RESSOURCEGROUP_TYPE]     NVARCHAR (50) NULL,
    [BASISENHED]              NVARCHAR (50) NULL,
    [ENHEDSPRIS]              FLOAT (53)    NULL,
    [PRODUKTBOGFØRINGSGRUPPE] NVARCHAR (50) NULL,
    CONSTRAINT [PK_DIM_RESSOURCEGROUP] PRIMARY KEY CLUSTERED ([RESSOURCEGROUP_ID] ASC)
);


GO

