CREATE TABLE [REPORTING].[DIM_KUNDE](
	[KUNDE_ID] [int] NOT NULL,
	[KUNDEAKTIV] [tinyint] NULL,
	[KUNDECVR] [nvarchar](10) NULL,
	[KUNDENAVN] [nvarchar](100) NULL,
	[KUNDEPOSTNR] [nvarchar](10) NULL,
	[KUNDEBYNAVN] [nvarchar](100) NULL,
	[DANMARK] [int] NULL,
	[KUNDESTARTDATO] [datetime2](0) NULL,
	[KUNDESLUTDATO] [datetime2](0) NULL,
	[FORHANDLER_ID] [int] NULL,
	[FORHANDLERNAVN] [nvarchar](200) NULL,
	[FORHANDLERCVR] [nvarchar](8) NULL,
	[FORHANDLERAKTIV] [smallint] NULL,
	[FORHANDLERPOSTNR] [nvarchar](4) NULL,
	[FORHANDLERKOMMUNE] [int] NULL,
	[FORHANDLERKLASSE] [nvarchar](50) NULL,
	[KONKURS_INKASSO_DUBIØS] [int] NULL,
 CONSTRAINT [PK_DimKunde] PRIMARY KEY CLUSTERED 
(
	[KUNDE_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


