CREATE TABLE [REPORTING].[DIM_KUNDE] (
    [KUNDE_ID]          INT            NOT NULL,
    [KUNDEAKTIV]        TINYINT        NULL,
    [KUNDECVR]          NVARCHAR (10)  NULL,
    [KUNDENAVN]         NVARCHAR (100) NULL,
    [KUNDEPOSTNR]       NVARCHAR (10)  NULL,
    [KUNDEBYNAVN]       NVARCHAR (100) NULL,
    [DANMARK]           INT            NULL,
    [KUNDESTARTDATO]    DATETIME2 (0)  NULL,
    [KUNDESLUTDATO]     DATETIME2 (0)  NULL,
    [FORHANDLER_ID]     INT            NULL,
    [FORHANDLERNAVN]    NVARCHAR (200) NULL,
    [FORHANDLERCVR]     NVARCHAR (8)   NULL,
    [FORHANDLERAKTIV]   SMALLINT       NULL,
    [FORHANDLERPOSTNR]  NVARCHAR (4)   NULL,
    [FORHANDLERKOMMUNE] INT            NULL,
    [FORHANDLERKLASSE]  NVARCHAR (50)  NULL,
    CONSTRAINT [PK_DimKunde] PRIMARY KEY CLUSTERED ([KUNDE_ID] ASC)
);


GO

