CREATE TABLE [REPORTING].[DIM_INVOICEGROUP] (
    [INVOICEGROUP_ID]   INT           NOT NULL,
    [INVOICEGROUP_NAME] NVARCHAR (50) NULL,
    [SYSTEM]            SMALLINT      NULL,
    [DATA]              SMALLINT      NULL,
    [EVENT]             SMALLINT      NULL,
    [LOAD_DATO]         DATE          NULL,
    CONSTRAINT [DIMINVOICEGROUP_PK] PRIMARY KEY CLUSTERED ([INVOICEGROUP_ID] ASC)
);


GO

