CREATE TABLE [REPORTING].[FACT_OMSÆTNING_TOTAL](
	[DATE_ID] [date] NOT NULL,
	[BUDGET] [bigint] NULL,
	[OMSÆTNING] [bigint] NULL,
 CONSTRAINT [PK_FACT_OMSÆTNING_TOTAL] PRIMARY KEY CLUSTERED 
(
	[DATE_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


