CREATE TABLE [REPORTING].[FACT_OMSÆTNING](
--DIM REFERENCES 
	[KUNDE_ID] [int] NULL,
	[RESSOURCEGROUP_ID] [int] NULL,
	[DATE_ID] [date] NULL,
--ATTRIBUTS
	[LINJE_NR] [int] NOT NULL,
	[BOGFØRINGSDATO] [date] NULL,
	[FAKTURA_NR] [int] NOT NULL,
	[BESKRIVELSE] [varchar](max) NULL,
	[LINJE_RABAT] [decimal](38, 20) NULL,
	[LINJE_RABAT_BELØB] [decimal](38, 20) NULL,
	[LOAD_DATO] [datetime2](0) NULL,
--MEASURES	
	[ANTAL_ENHEDER] [decimal](38, 20) NULL,
	[ENHEDSPRIS] [decimal](38, 20) NULL,
	[BELØB_EKSKL_MOMS] [decimal](38, 20) NULL
	
 CONSTRAINT [PK_FACT_OMSÆTNING] PRIMARY KEY CLUSTERED 
(
	[LINJE_NR] ASC,
	[FAKTURA_NR] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


