CREATE TABLE [REPORTING].[FACT_OMSÆTNING](
	[LINJE_NR] [int] NOT NULL,
	[BOGFØRINGSDATO] [date] NULL,
	[BETALINGSFRIST] [date] NULL,
	[FAKTURA_NR] [int] NOT NULL,
	[BESKRIVELSE] [varchar](max) NULL,
	[KUNDE_ID] [int] NULL,
	[RESSOURCEGROUP_ID] [int] NULL,
	[ANTAL_ENHEDER] [decimal](38, 20) NULL,
	[ENHEDSPRIS] [decimal](38, 20) NULL,
	[BELØB_EKSKL_MOMS] [decimal](38, 20) NULL,
	[LINJE_RABAT] [decimal](38, 20) NULL,
	[LINJE_RABAT_BELØB] [decimal](38,20) NULL,
	[LOAD_DATO] [datetime2](0) NULL,

	CONSTRAINT PK_FACT_OMSÆTNING PRIMARY KEY (LINJE_NR, FAKTURA_NR)
)

