CREATE TABLE [REPORTING].[FACT_MOBIL_OPKALD] (
    [FACT_MOBIL_OPKALD_ID]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [DATE_ID]                DATETIME2 (0)   NULL,
    [ABONNEMENT_ID]          BIGINT          NULL,
    [KUNDE_ID]               INT             NULL,
    [PRODUCT_ID]             BIGINT          NULL,
    [INVOICEGROUP_ID]        INT             NULL,
    [ANTAL_UDGAAENDE_OPKALD] INT             NULL,
    [VARIGHED_TIMER]         DECIMAL (36, 4) NULL,
    [PRIS]                   DECIMAL (36, 4) NULL,
    [OMKOSTNING]             DECIMAL (36, 4) NULL,
    [LOAD_DATE]              DATETIME2 (0)   NULL,
    CONSTRAINT [FACT_MOBIL_OPKALD_PK] PRIMARY KEY CLUSTERED ([FACT_MOBIL_OPKALD_ID] ASC),
    CONSTRAINT [FACT_MOBIL_OPKALD_UK] UNIQUE NONCLUSTERED ([ABONNEMENT_ID] ASC, [DATE_ID] ASC, [INVOICEGROUP_ID] ASC)
);


GO

