CREATE TABLE [REPORTING].[FACT_MOBIL_DATAFORBRUG_DETAIL](
	[FACT_MOBIL_DATAFORBRUG_DETAIL_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DATE_ID] [datetime2](0) NULL,
	[ABONNEMENT_ID] [bigint] NULL,
	[KUNDE_ID] [int] NULL,
	[INVOICEGROUP_ID] [int] NULL,
	[PRODUKT_ID] [bigint] NULL,
	[VOLUME_GB] [decimal](36, 10) NULL,
	[COST] [decimal](36, 10) NULL,
 CONSTRAINT [FACT_MOBIL_DATAFORBRUG_DETAIL_PK] PRIMARY KEY CLUSTERED 
(
	[FACT_MOBIL_DATAFORBRUG_DETAIL_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [FACT_MOBIL_DATAFORBRUG_DETAIL_UK] UNIQUE NONCLUSTERED 
(
	[ABONNEMENT_ID] ASC,
	[INVOICEGROUP_ID] ASC,
	[DATE_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


