CREATE TABLE [REPORTING].[FACT_OMSÆTNING] (
    [RÆKKE_ID]           INT              NOT NULL,
    [FAKTURA_LOBENUMMER] INT              NULL,
    [FAKTURA_NR]         INT              NULL,
    [BOGFØRINGSDATO]     DATE             NULL,
    [BETALINGSFRIST]     DATE             NULL,
    [KUNDE_ID]           INT              NULL,
    [BESKRIVELSE]        VARCHAR (MAX)    NULL,
    [RESSOURCEGROUP_ID]  INT              NULL,
    [ANTAL_ENHEDER]      DECIMAL (38, 20) NULL,
    [ENHEDSPRIS]         DECIMAL (38, 20) NULL,
    [LINJE_RABAT]        SMALLINT         NULL,
    [LOAD_DATO]          DATETIME2 (0)    NULL,
    [BELØB_EKSKL_MOMS]   DECIMAL (38, 20) NULL,
    CONSTRAINT [PK_FACT_OMSÆTNING] PRIMARY KEY CLUSTERED ([RÆKKE_ID] ASC)
);


GO

CREATE NONCLUSTERED INDEX [IDX_OMSÆTNING]
    ON [REPORTING].[FACT_OMSÆTNING]([FAKTURA_NR] ASC, [BOGFØRINGSDATO] ASC, [KUNDE_ID] ASC, [RESSOURCEGROUP_ID] ASC);


GO

