CREATE TABLE [REPORTING].[FACT_CHURN](
	[FACT_CHURN_PK] [int] IDENTITY(1,1) NOT NULL,
	[PARTNER_ID] [int] NULL,
	[DATE_ID] [date] NULL,
	[FISCAL_YEAR_START_DT] [date] NULL,
	[NUMBER_OF_MONTHS_PASSED] [int] NULL,
	[NUMBER_OF_CHURNED_CUSTOMERS] [int] NULL,
	[NUMBER_OF_OFFERS] [int] NULL,
	[NUMBER_OF_ACTIVE_CUSTOMERS] [int] NULL,
	[FIRST_DEVISION] [decimal](20, 10) NULL,
	[CHURN_PCT] [decimal](20, 10) NULL,
PRIMARY KEY CLUSTERED 
(
	[FACT_CHURN_PK] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_FACT_CHURN] UNIQUE NONCLUSTERED 
(
	[PARTNER_ID] ASC,
	[DATE_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


