CREATE VIEW [BASELINE].[DIM_PARTNER_V]
AS

SELECT 
F_ID AS PARTNER_ID,
F.NAVN AS PARTNER_NAME,
F.CVR AS PARTNER_CVR,
F.AKTIV AS PARTNER_ACTIVE,
F.HPBX AS PARTNER_HPBX,
FS.VAL AS PARTNER_CLASS

FROM ADMIN.FORHANDLERE F 
LEFT JOIN ADMIN.FORHANDLERSETTINGS FS ON F.F_ID=FS.FORHANDLERID

WHERE FS.SETTING='PARTNER_CLASS'

GO


