CREATE VIEW [REPORTING].[CUSTOMERS_TOTAL_ADDED_LEAVING_GROSS_V]
AS

SELECT DATE_ID , [70] AS NUMBER_OF_CUSTOMERS, [72] AS ARRIVING_CUSTOMERS, [73] AS LEAVING_CUSTOMERS, [72]-[73] AS GROSS_ADDED_CUSTOMERS 
FROM 
(
	SELECT * FROM   
	(
		SELECT 
			REALISERET,
			KPI_ID, 
			DATE_ID
	
		FROM 
			REPORTING.FACT_KPI F
	
	) T 
	PIVOT(
		SUM(REALISERET) 
		FOR KPI_ID IN ([70],[72],[73]) 
		  ) AS PIVOT_TABLE
	) I


