CREATE TABLE [BASELINE].[CHURN_PER_PARTNER](
	[PARTNER_ID] [int] NULL,
	[LAST_DAY_OF_MONTH] [date] NULL,
	[FISCAL_YEAR_START_DT] [date] NULL,
	[NUMBER_OF_MONTHS_PASSED] [int] NULL,
	[NUMBER_OF_CHURNED_CUSTOMERS] [int] NULL,
	[NUMBER_OF_OFFERS] [int] NULL,
	[NUMBER_OF_ACTIVE_CUSTOMERS] [int] NULL,
	[FIRST_DEVISION] [decimal](20, 10) NULL,
	[CHURN_PCT] [decimal](20, 10) NULL,
 CONSTRAINT [UK_CHURN_PER_PARTNER] UNIQUE NONCLUSTERED 
(
	[PARTNER_ID] ASC,
	[LAST_DAY_OF_MONTH] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO