CREATE TABLE [BASELINE].[TELESERVICECODE] (
    [TSCODE]             INT           NOT NULL,
    [TSCODE_DESCRIPTION] VARCHAR (MAX) NULL,
    CONSTRAINT [PK_TELESERVICECODE] PRIMARY KEY CLUSTERED ([TSCODE] ASC)
);


GO

