CREATE TABLE [navision].[Uni-tel_AS_Resource] (
    [timestamp]                      DATETIME2 (0)   NULL,
    [No_]                            INT             NULL,
    [Type]                           INT             NULL,
    [Name]                           NVARCHAR (50)   NULL,
    [Search Name]                    NVARCHAR (50)   NULL,
    [Name 2]                         NVARCHAR (50)   NULL,
    [Address]                        NVARCHAR (50)   NULL,
    [Address 2]                      NVARCHAR (50)   NULL,
    [City]                           NVARCHAR (30)   NULL,
    [Social Security No_]            NVARCHAR (30)   NULL,
    [Job Title]                      NVARCHAR (30)   NULL,
    [Education]                      NVARCHAR (30)   NULL,
    [Contract Class]                 NVARCHAR (50)   NULL,
    [Employment Date]                DATETIME2 (0)   NULL,
    [Resource Group No_]             NVARCHAR (20)   NULL,
    [Global Dimension 1 Code]        NVARCHAR (20)   NULL,
    [Global Dimension 2 Code]        NVARCHAR (20)   NULL,
    [Base Unit of Measure]           NVARCHAR (10)   NULL,
    [Direct Unit Cost]               DECIMAL (10)    NULL,
    [Indirect Cost _]                DECIMAL (10)    NULL,
    [Unit Cost]                      DECIMAL (10)    NULL,
    [Profit _]                       DECIMAL (10)    NULL,
    [Price_Profit Calculation]       INT             NULL,
    [Unit Price]                     DECIMAL (10)    NULL,
    [Vendor No_]                     NVARCHAR (20)   NULL,
    [Last Date Modified]             DATETIME2 (0)   NULL,
    [Blocked]                        SMALLINT        NULL,
    [Gen_ Prod_ Posting Group]       NVARCHAR (10)   NULL,
    [Picture]                        VARBINARY (MAX) NULL,
    [Post Code]                      NVARCHAR (20)   NULL,
    [County]                         NVARCHAR (30)   NULL,
    [Automatic Ext_ Texts]           SMALLINT        NULL,
    [No_ Series]                     NVARCHAR (10)   NULL,
    [Tax Group Code]                 NVARCHAR (10)   NULL,
    [VAT Prod_ Posting Group]        NVARCHAR (10)   NULL,
    [Country_Region Code]            NVARCHAR (10)   NULL,
    [IC Partner Purch_ G_L Acc_ No_] NVARCHAR (20)   NULL,
    [Use Time Sheet]                 SMALLINT        NULL,
    [Time Sheet Owner User ID]       NVARCHAR (50)   NULL,
    [Time Sheet Approver User ID]    NVARCHAR (50)   NULL,
    [Service Zone Filter]            NVARCHAR (10)   NULL,
    [load_dato]                      DATETIME2 (0)   NULL
);


GO

