CREATE TABLE [admin].[cust] (
    [custid]                INT            NULL,
    [navn]                  NVARCHAR (100) NULL,
    [gade]                  NVARCHAR (100) NULL,
    [nr]                    NVARCHAR (5)   NULL,
    [etage]                 NVARCHAR (5)   NULL,
    [side]                  NVARCHAR (10)  NULL,
    [postnr]                NVARCHAR (10)  NULL,
    [bynavn]                NVARCHAR (100) NULL,
    [tlf]                   NVARCHAR (10)  NULL,
    [fax]                   NVARCHAR (10)  NULL,
    [email]                 NVARCHAR (100) NULL,
    [exportbilling]         INT            NULL,
    [ignoreinvoice]         SMALLINT       NULL,
    [forhandlerid]          INT            NULL,
    [partner_custid]        NVARCHAR (50)  NULL,
    [cvr]                   NVARCHAR (10)  NULL,
    [vejkode]               NVARCHAR (4)   NULL,
    [komkode]               NVARCHAR (4)   NULL,
    [ref]                   NVARCHAR (100) NULL,
    [ean]                   NVARCHAR (30)  NULL,
    [adminuser]             NVARCHAR (30)  NULL,
    [adminpass]             NVARCHAR (255) NULL,
    [active]                TINYINT        NULL,
    [admin_email]           NVARCHAR (50)  NULL,
    [created]               DATETIME2 (0)  NULL,
    [country_id]            INT            NULL,
    [bookieuser]            NVARCHAR (30)  NULL,
    [bookiepass]            NVARCHAR (255) NULL,
    [betalingsbetingelser]  NVARCHAR (255) NULL,
    [rykkerkode]            NVARCHAR (255) NULL,
    [spaerret]              TINYINT        NULL,
    [momskode]              NVARCHAR (255) NULL,
    [po]                    NVARCHAR (255) NULL,
    [pbs]                   SMALLINT       NULL,
    [postal_country_id]     INT            NULL,
    [address2]              NVARCHAR (150) NULL,
    [responsible_emails_id] INT            NULL,
    [dawa_id]               NVARCHAR (36)  NULL,
    [load_dato]             DATETIME2 (0)  NULL
);


GO

