CREATE VIEW [REPORTING].[FACT_KPI_V]
AS
--THE PURPOSE OF THE VIEW IS TO ESTABLISH ONE OBJECT CONTAIN ALL DAGE FOR THE HIGHCARTS GRAPHS- PARTNER STATICTICS / KPIS
SELECT F.KPI_ID, F.FORHANDLER_ID, K.FORHANDLER_NAVN, F.DATE_ID, CAST (F.REALISERET AS BIGINT) AS REALISERET, CAST (F.MÅL AS BIGINT) AS MÅL, 
D.KPI_NAVN, D.INFO_TEKST, D.ENHED, D.SORTERING
FROM REPORTING.FACT_KPI F
INNER JOIN REPORTING.DIM_KPI D ON f.KPI_ID=D.KPI_ID
LEFT JOIN (SELECT DISTINCT(FORHANDLER_ID), FORHANDLERNAVN AS FORHANDLER_NAVN FROM REPORTING.DIM_KUNDE) K ON K.FORHANDLER_ID=F.FORHANDLER_ID
WHERE D.AKTIV=1;

