CREATE VIEW [REPORTING].[FACT_KPI_V]
AS
--FORMÅLET ER AT ETABLERE ÉT OBJEKT, SOM JAVA SCRIPTS KAN FORESPØRGE I
SELECT F.KPI_ID, F.FORHANDLER_ID, K.FORHANDLER_NAVN, F.DATE_ID, F.REALISERET as "Realiseret", F.MÅL AS "Mål", D.KPI_NAVN
FROM REPORTING.FACT_KPI F
INNER JOIN REPORTING.DIM_KPI D ON f.KPI_ID=D.KPI_ID
LEFT JOIN (SELECT DISTINCT(FORHANDLER_ID), FORHANDLERNAVN AS FORHANDLER_NAVN FROM REPORTING.DIM_KUNDE) K ON K.FORHANDLER_ID=F.FORHANDLER_ID
WHERE D.AKTIV=1
GO


