--14.10.2021: THE PURPOSE OF THIS VIEW IS TO PRESENT DATA TO THE FINANCIAL FUNCTION 
CREATE VIEW REPORTING.KICKBACK_OVERVIEW_V
AS
SELECT K.FORHANDLERID, F.NAVN AS FORHANDLERNAVN, K.YEAR, K.MONTH, SUM(K.AMOUNT) AS AMOUNT, K.INVOICED 
FROM ADMIN.KICKBACK_SUM K
LEFT JOIN ADMIN.FORHANDLERE F ON F.F_ID=K.FORHANDLERID
WHERE K.YEAR >= YEAR(GETDATE())-1
GROUP BY K.FORHANDLERID, F.NAVN, K.YEAR, K.MONTH, K.INVOICED