CREATE VIEW REPORTING.DIM_PARTNER_V
--CONCIDER IF THE DIMENSION SHOULD BE BUILD AS A REAL TABLE WITH A PK
--CONCIDER IF THE DATASOURCE SHOULD BE ADMIN.FORHANDLERE
AS
SELECT 
DISTINCT(FORHANDLER_ID) AS PARTNER_ID, FORHANDLERNAVN AS PARTNER_NAME, FORHANDLERCVR AS PARTNER_CVR, 
FORHANDLERAKTIV AS PARTNER_ACTIVE, FORHANDLERKLASSE AS PARTNER_CLASS, K.KONKURS_INKASSO_DUBIØS AS BANCRUPT 
FROM REPORTING.DIM_KUNDE K
;
