ALTER VIEW REPORTING.ABN_OPRETTELSER_V
--23-09-2021 OPRETTET TIL RAPPORT I POWER BI
AS
(
SELECT COUNT (*) AS [NYOPRETTEDE ABN], YEAR(OPRETTET) AS ÅR, MONTH(OPRETTET) AS MÅNED, ABN_NAVN AS ABONNOMENT
FROM REPORTING.DIM_MOBIL_ABONNEMENT
WHERE YEAR(OPRETTET)>=
		(SELECT 
		CASE
		  WHEN MONTH(GETDATE()) IN (1,2,3) THEN YEAR(GETDATE())-1
		  ELSE YEAR(GETDATE())
		END)
GROUP BY ABN_NAVN, YEAR(OPRETTET), MONTH(OPRETTET)
)