ALTER VIEW [REPORTING].[ABN_OPRETTELSER_V]
--26-10-2021 CREATED FOR POWER BI REPORTING
AS
(
SELECT COUNT (*) AS [NYOPRETTEDE ABN], YEAR(OPRETTET) AS ÅR, MONTH(OPRETTET) AS MÅNED, CAST (EOMONTH(OPRETTET) AS DATE) AS DATO, ABN_NAVN AS ABONNOMENT
FROM REPORTING.DIM_MOBIL_ABONNEMENT
WHERE YEAR(OPRETTET)>=
		(SELECT 
		CASE
		  WHEN MONTH(GETDATE()) IN (1,2,3) THEN YEAR(GETDATE())-1
		  ELSE YEAR(GETDATE())
		END)
GROUP BY ABN_NAVN, YEAR(OPRETTET), MONTH(OPRETTET), CAST (EOMONTH(OPRETTET) AS DATE)
)
