
CREATE FUNCTION [BASELINE].[ANTAL_KUNDER_TOTAL_F] (@OPGORELSES_DATO DATE)
RETURNS INT

BEGIN
  DECLARE @ANTAL_KUNDER_TOTAL AS INT;
  
  SELECT  @ANTAL_KUNDER_TOTAL=SUM(C2.CUSTNUMBER) 
          FROM ADMIN.CUSTSTATS C2 
          WHERE CAST(RDATE AS DATE)=@OPGORELSES_DATO;
            
  RETURN @ANTAL_KUNDER_TOTAL;
            
END;

GO

