CREATE FUNCTION BASELINE.[ANTAL_TILBUD_F] (@FINANSAAR_START DATE, @FINANSAAR_SLUT DATE)
RETURNS INT

BEGIN
  DECLARE @ANTAL_TILBUD AS INT;
  
  SELECT  @ANTAL_TILBUD=
	COUNT (DISTINCT CH.CUST) 
	FROM ADMIN.CHURN CH
	LEFT JOIN ADMIN.CUST C ON C.CUSTID=CH.CUST
	WHERE CH.DT BETWEEN @FINANSAAR_START AND @FINANSAAR_SLUT  
	AND CH.CUST NOT IN (SELECT CUSTID FROM ADMIN.TURNOVER WHERE AMOUNT>0) 
	AND C.ACTIVE=0 
	AND C.FORHANDLERID NOT IN (12,43,0)  --UNITEL SELV, CONNECTION.DK, UNICOM.DK
	AND C.CREATED>'2015-01-01'
	AND C.CUSTID NOT IN (SELECT CUSTID FROM ADMIN.CUSTSETTINGS WHERE SETTING='BILL_TO_CUST');

	RETURN @ANTAL_TILBUD;
	END;

GO

