CREATE FUNCTION BASELINE.[ANTAL_CHURNEDE_KUNDER_F] (@FINANSAAR_START DATE, @FINANSAAR_SLUT DATE)
RETURNS INT

BEGIN
  DECLARE @ANTAL_CHURNEDE_KUNDER AS INT;
  
  SELECT  @ANTAL_CHURNEDE_KUNDER=
	COUNT (DISTINCT CH.CUST) 
	FROM ADMIN.CHURN CH 
	LEFT JOIN ADMIN.CUST C ON C.CUSTID=CH.CUST 
	WHERE CH.DT BETWEEN '2019-07-01' AND '2020-06-30'  
	AND C.ACTIVE=0 
	AND C.FORHANDLERID<>12 --CONNECTION A/S SORTERES FRA. ER DER ANDRE DER BØR SORTERES FRA?
	
	RETURN @ANTAL_CHURNEDE_KUNDER;
	END;

GO

