CREATE TABLE [REPORTING].[DIM_PARTNER](
	[PARTNER_ID] [int] NOT NULL,
	[PARTNER_NAME] [nvarchar](200) NULL,
	[PARTNER_CVR] [nvarchar](50) NULL,
	[PARTNER_ACTIVE] [smallint] NULL,
	[PARTNER_HPBX] [smallint] NULL,
	[PARTNER_CLASS] [nvarchar](200) NULL,
 CONSTRAINT [PK_DIM_PARTNER] PRIMARY KEY CLUSTERED 
(
	[PARTNER_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


