ALTER PROCEDURE REPORTING.TRUNC_INSERT_BEHOLDNING_ABN_MND
AS

TRUNCATE TABLE REPORTING.BEHOLDNING_ABN_MND;

--Chr. 27.9.2021 Usikkerheden i tallene består i, at den aktuelle abonnomentstype (fx Dk-stor) vises
--Da kunderne kan skifte abonnoment over tid ses der alene på aktulle og forrige år. 
SELECT 
COUNT(DISTINCT ABN_ID) AS ANTAL_DISTINKTE_ABN, R.ABNNAME, YEAR(DATE_ID) AS ÅR, MONTH(DATE_ID) AS MÅNED,
COUNT(DISTINCT ABN_ID)-LAG (COUNT(DISTINCT ABN_ID)) OVER (PARTITION BY R.ABNNAME ORDER BY YEAR(DATE_ID), MONTH(DATE_ID) ASC) AS NETTO_VAEKST
INTO REPORTING.BEHOLDNING_ABN_MND
--KILDEN ER ET VIEW SOM UDGØR EN UNION AF ADMIN.MOB
FROM BASELINE.MOBIL_ABONNOMENTER_PR_MND_V V
LEFT JOIN RATING.MOB_ABN R ON V.ABN=R.ID
AND YEAR(DATE_ID)>=YEAR(GETDATE())-1 
GROUP BY R.ABNNAME, YEAR(DATE_ID), MONTH(DATE_ID);

