CREATE PROCEDURE [REPORTING].[DELETE_INSERT_FACT_KPI_OMSÆTNING]
AS 
BEGIN
--THIS PROCEDURES DELETES AND INSERTES VALUES INTO REPORTING.FACT_KPI - SOURCE FOR THE DEALER-KPI SITE
IF OBJECT_ID('REPORTING.FACT_KPI', 'U') IS NOT NULL 

--ALL DATA IN THE GROUP TURNOVER ("Omsætning") WILL BE DELETED IN FACT_KPI
	PRINT 'DELETES ALL DATA REGARDING REPORTS IN REPORTING.FACT_KPI ';
	DELETE FROM REPORTING.FACT_KPI WHERE KPI_ID IN (SELECT DISTINCT KPI_ID FROM REPORTING.DIM_KPI WHERE GRUPPERING_NAVN='Omsætning');

--KPI "TOTAL TURNOVER" IS INSERTED IN FACT_KPI
	PRINT 'INSERTS TURNOVER TOTAL I REPORTING.FACT_KPI';
	INSERT INTO REPORTING.FACT_KPI (REALISERET, FORHANDLER_ID,DATE_ID,KPI_ID)
	
		SELECT ROUND(SUM(F.BELØB_EKSKL_MOMS),0) AS REALISERET, K.FORHANDLER_ID AS FORHANDLER_ID, EOMONTH(F.BOGFØRINGSDATO) AS DATE_ID,
	(SELECT KPI_ID FROM REPORTING.DIM_KPI WHERE KPI_NAVN='Omsætning i alt') AS KPI_ID
	
	FROM REPORTING.FACT_OMSÆTNING F
	INNER JOIN REPORTING.DIM_KUNDE K ON K.KUNDE_ID=F.KUNDE_ID

--THE DATA IS CURRENTED FOR THE CURRENT AND LAST YEAR
	WHERE EOMONTH(F.BOGFØRINGSDATO) IN (SELECT LASTDAYOFMONTH FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK)
	
	GROUP BY EOMONTH(F.BOGFØRINGSDATO), FORHANDLER_ID;

	PRINT 'TURNOVER TARGETS IN REPORTING_FACT_KPI CALCULATED AND UPDATED ';

	MERGE REPORTING.FACT_KPI T
	USING 
		(
		SELECT BUDGET/12 AS MÅL, 
		FORHANDLER_ID, 
		D.LASTDAYOFMONTH AS DATE_ID,
		(SELECT KPI_ID FROM REPORTING.DIM_KPI WHERE KPI_NAVN='Omsætning i alt') AS KPI_ID
		FROM NAVISION.FORHANDLER_BUDGET B
		--THE JOIN CREATES A ROW PR. MONTH FOR THE FISCALYEAR STORED IN NAVISION.FORHANDLER_BUDGET
		JOIN (SELECT DISTINCT LASTDAYOFMONTH, FISCALYEAR FROM BASELINE.DIM_DATO) D ON B.FISCALYEAR=D.FISCALYEAR
		) S
	ON T.KPI_ID=S.KPI_ID AND T.FORHANDLER_ID=S.FORHANDLER_ID AND T.DATE_ID=S.DATE_ID
	WHEN MATCHED THEN 
	UPDATE SET T.MÅL=S.MÅL;

--KPI "GNM, OMSÆTNING PR. KUNDE" INDSÆTTES I FACT_KPI
	PRINT 'GNM REVENUE PER. CUSTOMER INSERTED IN REPORTING.FACT_KPI ';
INSERT INTO REPORTING.FACT_KPI (REALISERET, FORHANDLER_ID, DATE_ID, KPI_ID)

	SELECT ROUND(OMSAETNING_I_ALT/CS.CUSTNUMBER,0) AS REALISERET, I.FORHANDLER_ID, I.DATE_ID, I.KPI_ID
	FROM
	--INNER SELECT IS USED TO ACHIEVE THE SAME GRANUALITY IN NUMBER OF CUSTOMERS AND TURNOVER PER DEALER AND MONTH
				(
				SELECT SUM(F.BELØB_EKSKL_MOMS) AS OMSAETNING_I_ALT, K.FORHANDLER_ID AS FORHANDLER_ID, EOMONTH(F.BOGFØRINGSDATO) AS DATE_ID,
				(SELECT KPI_ID FROM REPORTING.DIM_KPI WHERE KPI_NAVN='Gnm. omsætning pr. kunde') AS KPI_ID
	
				FROM REPORTING.FACT_OMSÆTNING F
				INNER JOIN REPORTING.DIM_KUNDE K ON K.KUNDE_ID=F.KUNDE_ID

				--INSERTS DATA FOR CURRENT AND LAST YEAR 
				WHERE EOMONTH(F.BOGFØRINGSDATO) IN (SELECT LASTDAYOFMONTH FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK)
	
				GROUP BY EOMONTH(F.BOGFØRINGSDATO), FORHANDLER_ID
				) I

	LEFT JOIN ADMIN.CUSTSTATS CS ON (CS.F_ID=I.FORHANDLER_ID AND CAST(CS.RDATE AS DATE)=I.DATE_ID);
	
--KPI REVENUE PER PRODUCT ACCOUNTING GROUP INTO REPORTING.FACT_KPI
	PRINT 'REVENUE PER. PRODUCT BOOKING GROUP INSERTED IN REPORTING.FACT_KPI ';
	INSERT INTO REPORTING.FACT_KPI (REALISERET, FORHANDLER_ID, DATE_ID, KPI_ID)

	SELECT ROUND( SUM(F.BELØB_EKSKL_MOMS), 1) AS REALISERET, K.FORHANDLER_ID AS FORHANDLER_ID, EOMONTH(F.BOGFØRINGSDATO) AS DATE_ID, D.KPI_ID 
	
	FROM REPORTING.FACT_OMSÆTNING F
	LEFT JOIN REPORTING.DIM_RESSOURCEGROUP R ON R.RESSOURCEGROUP_ID=F.RESSOURCEGROUP_ID
	INNER JOIN REPORTING.DIM_KUNDE K ON K.KUNDE_ID=F.KUNDE_ID
	INNER JOIN REPORTING.DIM_KPI D ON R.PRODUKTBOGFØRINGSGRUPPE=D.ALTERNATIVT_KPI_NAVN
	
	WHERE EOMONTH(F.BOGFØRINGSDATO) IN (SELECT LASTDAYOFMONTH FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK)
	GROUP BY EOMONTH(F.BOGFØRINGSDATO), FORHANDLER_ID, D.KPI_ID;
END;
