CREATE PROCEDURE [REPORTING].[DELETE_INSERT_FACT_KPI_TIL_OG_AFGANG_KUNDER]
AS 
BEGIN
IF OBJECT_ID('REPORTING.FACT_KPI', 'U') IS NOT NULL 

PRINT 'Der slettes rækker i REPORTING.FACT_KPI for to KPIer - afgang og tilgang af kunder';

DELETE FROM REPORTING.FACT_KPI WHERE KPI_ID=(SELECT KPI_ID FROM REPORTING.DIM_KPI WHERE KPI_NAVN = 'Tilgang af kunder');
DELETE FROM REPORTING.FACT_KPI WHERE KPI_ID=(SELECT KPI_ID FROM REPORTING.DIM_KPI WHERE KPI_NAVN = 'Afgang af kunder');

		
PRINT 'KPIet "Tilgang af kunder" indsættes i FACT_KPI';
	
	INSERT INTO REPORTING.FACT_KPI (REALISERET, FORHANDLER_ID, DATE_ID, KPI_ID)
	
	SELECT 
	TILGANG_KUNDER AS REALISERET,
	A.FORHANDLER_ID,
	T.LASTDAYOFMONTH as DATE_ID, 
	(SELECT KPI_ID FROM REPORTING.DIM_KPI WHERE KPI_NAVN='Tilgang af kunder') AS KPI_ID
		
	FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK T  
		INNER JOIN   
			(
			SELECT COUNT(DISTINCT K.KUNDE_ID) AS TILGANG_KUNDER, EOMONTH(K.KUNDESTARTDATO) AS LAST_DAY_OF_MONTH_DT,  K.FORHANDLER_ID
			FROM REPORTING.DIM_KUNDE K
			GROUP BY EOMONTH(KUNDESTARTDATO), K.FORHANDLER_ID
			) A 
	ON T.LASTDAYOFMONTH=A.LAST_DAY_OF_MONTH_DT;

PRINT 'KPI "Afgang af kunder indsættes i FACT_KPI'
	INSERT INTO REPORTING.FACT_KPI (REALISERET, FORHANDLER_ID, DATE_ID, KPI_ID)
	
		SELECT 
		AFGANG_KUNDER AS REALISERET,
		A.FORHANDLER_ID,
		T.LASTDAYOFMONTH as DATE_ID, 
		(SELECT KPI_ID FROM REPORTING.DIM_KPI WHERE KPI_NAVN='Afgang af kunder') AS KPI_ID
		
		FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK T  
			INNER JOIN   
				(
				SELECT COUNT (DISTINCT K.KUNDE_ID) AS AFGANG_KUNDER, EOMONTH(KUNDESLUTDATO) AS LAST_DAY_OF_MONTH_DT, K.FORHANDLER_ID
				FROM REPORTING.DIM_KUNDE K
				WHERE UPPER(KUNDENAVN) NOT LIKE '%KONKURS%'
				GROUP BY EOMONTH(KUNDESLUTDATO), k.FORHANDLER_ID
				) A 
		ON T.LASTDAYOFMONTH=A.LAST_DAY_OF_MONTH_DT;
/*
Chr 23.6.2021
Tilgang af kunder er en simpel optælling af distinkte kunder pr. forhandler pr. måned baseret på feltet ADMIN.CUST.CREATED udstilles i REPORTING.DIM_KUNDE
Afgang af kunder beregnes ved at se ned i REPORTING.DIM_KUNDE, hvor grunddata udgøres af tabellen ADMIN.CHURN, som supplerer admin.cust med en kunde-slutdato efter 1.1.2016
*/
END;

GO

