CREATE PROCEDURE [REPORTING].[DELETE_INSERT_FACT_KPI_OMSÆTNING]
AS 
BEGIN
IF OBJECT_ID('REPORTING.FACT_KPI', 'U') IS NOT NULL 

--ALLE DATA I GRUPPEN "OMSÆTNING" SLETTES I FACT_KPI
	PRINT 'SLETTER ALLE DATA VEDR. OMSÆTNING I REPORTING.FACT_KPI' ;
	DELETE FROM REPORTING.FACT_KPI WHERE KPI_ID IN (SELECT DISTINCT KPI_ID FROM REPORTING.DIM_KPI WHERE GRUPPERING_NAVN='Omsætning');

--KPI "OMSÆTNING I ALT" INDSÆTTES I FACT_KPI
	PRINT 'INDSÆTTER OMSÆTNING I ALT I REPORTING.FACT_KPI';
	INSERT INTO REPORTING.FACT_KPI (REALISERET, FORHANDLER_ID,DATE_ID,KPI_ID)
	
		SELECT ROUND(SUM(F.BELØB_EKSKL_MOMS),0) AS REALISERET, K.FORHANDLER_ID AS FORHANDLER_ID, EOMONTH(F.BOGFØRINGSDATO) AS DATE_ID,
	(SELECT KPI_ID FROM REPORTING.DIM_KPI WHERE KPI_NAVN='Omsætning i alt') AS KPI_ID
	
	FROM REPORTING.FACT_OMSÆTNING F
	INNER JOIN REPORTING.DIM_KUNDE K ON K.KUNDE_ID=F.KUNDE_ID
		
	--DER INDSÆTTES DATA FOR INDEVÆRENDE OG SIDSTE ÅR
	WHERE EOMONTH(F.BOGFØRINGSDATO) IN (SELECT LASTDAYOFMONTH FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK)
	
	GROUP BY EOMONTH(F.BOGFØRINGSDATO), FORHANDLER_ID;

	PRINT 'OMSÆTNINGSMÅL PR. FORHANDLER I REPORTING_FACT_KPI BEREGNES MIDLERTIDIGT SOM 1,25*OMSÆTNING';

	UPDATE REPORTING.FACT_KPI
	SET MÅL =ROUND(REALISERET*1.25,1)
	WHERE KPI_ID=(SELECT KPI_ID FROM REPORTING.DIM_KPI WHERE KPI_NAVN='Omsætning i alt'); 

	
--KPI "GNM, OMSÆTNING PR. KUNDE" INDSÆTTES I FACT_KPI
	PRINT 'GNM OMSÆTNING PR. KUNDE INDSÆTTES I REPORTING.FACT_KPI' ;
INSERT INTO REPORTING.FACT_KPI (REALISERET, FORHANDLER_ID, DATE_ID, KPI_ID)

	SELECT ROUND(OMSAETNING_I_ALT/CS.CUSTNUMBER,0) AS REALISERET, I.FORHANDLER_ID, I.DATE_ID, I.KPI_ID
	FROM
	--inner select anvendes for at opnå samme granualitet i antal kunder og omsætning pr. forhandler og måned
				(
				SELECT SUM(F.BELØB_EKSKL_MOMS) AS OMSAETNING_I_ALT, K.FORHANDLER_ID AS FORHANDLER_ID, EOMONTH(F.BOGFØRINGSDATO) AS DATE_ID,
				(SELECT KPI_ID FROM REPORTING.DIM_KPI WHERE KPI_NAVN='Gnm. omsætning pr. kunde') AS KPI_ID
	
				FROM REPORTING.FACT_OMSÆTNING F
				INNER JOIN REPORTING.DIM_KUNDE K ON K.KUNDE_ID=F.KUNDE_ID

				--DER INDSÆTTES DATA FOR INDEVÆRENDE OG SIDSTE ÅR
				WHERE EOMONTH(F.BOGFØRINGSDATO) IN (SELECT LASTDAYOFMONTH FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK)
	
				GROUP BY EOMONTH(F.BOGFØRINGSDATO), FORHANDLER_ID
				) I

	LEFT JOIN ADMIN.CUSTSTATS CS ON (CS.F_ID=I.FORHANDLER_ID AND CAST(CS.RDATE AS DATE)=I.DATE_ID);
	
--KPI OMSÆTNING PR.PRODUKTBOGFØRINGSGRUPPE INDSÆTTES I REPORTING.FACT_KPI 
	PRINT 'OMSÆTNING PR. PRODUKTBOGFØRINGSGRUPPE INDSÆTTES I REPORTING.FACT_KPI' ;
	INSERT INTO REPORTING.FACT_KPI (REALISERET, FORHANDLER_ID, DATE_ID, KPI_ID)

	SELECT ROUND( SUM(F.BELØB_EKSKL_MOMS), 1) AS REALISERET, K.FORHANDLER_ID AS FORHANDLER_ID, EOMONTH(F.BOGFØRINGSDATO) AS DATE_ID, D.KPI_ID 
	
	FROM REPORTING.FACT_OMSÆTNING F
	LEFT JOIN REPORTING.DIM_RESSOURCEGROUP R ON R.RESSOURCEGROUP_ID=F.RESSOURCEGROUP_ID
	INNER JOIN REPORTING.DIM_KUNDE K ON K.KUNDE_ID=F.KUNDE_ID
	INNER JOIN REPORTING.DIM_KPI D ON R.PRODUKTBOGFØRINGSGRUPPE=D.ALTERNATIVT_KPI_NAVN
	
	WHERE EOMONTH(F.BOGFØRINGSDATO) IN (SELECT LASTDAYOFMONTH FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK)
	GROUP BY EOMONTH(F.BOGFØRINGSDATO), FORHANDLER_ID, D.KPI_ID;
END;

GO

