ALTER PROCEDURE [REPORTING].[MERGE_FACT_OMSÆTNING]
AS 
BEGIN
IF OBJECT_ID('REPORTING.FACT_OMSÆTNING', 'U') IS NOT NULL 

PRINT ('MERGE FACT_OMSÆTNING');

MERGE [REPORTING].[FACT_OMSÆTNING] T
USING 
(
SELECT 
--DIM REFERENCES
KUNDE_ID,
RESSOURCEGROUP_ID,
DATE_ID,
--ATTRIBUTES
LINJE_NR,
FAKTURA_NR,
BOGFØRINGSDATO,
BESKRIVELSE,
LINJE_RABAT,
LINJE_RABAT_BELØB,
LOAD_DATO, 
--MEASURES
ANTAL_ENHEDER,
ENHEDSPRIS,
BELØB_EKSKL_MOMS

FROM BASELINE.FACT_OMSÆTNING_V
) S --SOURCE

ON S.LINJE_NR=T.LINJE_NR AND S.FAKTURA_NR=T.FAKTURA_NR

WHEN MATCHED THEN UPDATE SET 
--DIM ID
T.KUNDE_ID=S.KUNDE_ID,
T.RESSOURCEGROUP_ID=S.RESSOURCEGROUP_ID,
T.DATE_ID=S.DATE_ID,

--ATTRIBUTES
T.BOGFØRINGSDATO=S.BOGFØRINGSDATO,
T.BESKRIVELSE=S.BESKRIVELSE,
T.LINJE_RABAT=S.LINJE_RABAT,
T.LINJE_RABAT_BELØB=S.LINJE_RABAT_BELØB,
T.LOAD_DATO=S.LOAD_DATO,

--MEASURES
T.ANTAL_ENHEDER=S.ANTAL_ENHEDER,
T.ENHEDSPRIS=S.ENHEDSPRIS,
T.BELØB_EKSKL_MOMS=S.BELØB_EKSKL_MOMS

WHEN NOT MATCHED 
THEN INSERT 
(
--DIM_ID
KUNDE_ID, 
RESSOURCEGROUP_ID,
DATE_ID, 

--ATTRIBUTES
LINJE_NR,
FAKTURA_NR,
BOGFØRINGSDATO,
BESKRIVELSE,
LINJE_RABAT,
LINJE_RABAT_BELØB,
LOAD_DATO, 

--MEASURES
ANTAL_ENHEDER,
ENHEDSPRIS,
BELØB_EKSKL_MOMS
)
VALUES 
(
--DIM_ID
S.KUNDE_ID,
S.RESSOURCEGROUP_ID,
S.DATE_ID,

--ATTRIBUTES
S.LINJE_NR,
S.FAKTURA_NR,
S.BOGFØRINGSDATO,
S.BESKRIVELSE,
S.LINJE_RABAT,
S.LINJE_RABAT_BELØB,
S.LOAD_DATO,

--MEASURES
S.ANTAL_ENHEDER,
S.ENHEDSPRIS,
S.BELØB_EKSKL_MOMS
);
/*
WHEN SOURCE IS NOT MATCHED THEN DELETE is not used here as the temp in BASELINE.FACT_OMSÆTNING_V normaly
only will contain currnet year. We do not need the previous years to be deleted. 
*/
END;



