EXECUTE [REPORTING].MERGE_FACT_FAKTURERINGSGRUNDLAG

CREATE PROCEDURE [REPORTING].[MERGE_FACT_FAKTURERINGSGRUNDLAG]
AS 
BEGIN
IF OBJECT_ID('REPORTING.FACT_FAKTURERINGSGRUNDLAG', 'U') IS NOT NULL 

PRINT ('MERGE FACT_FAKTURERINGSGRUNDLAG');

MERGE [REPORTING].[FACT_FAKTURERINGSGRUNDLAG] T
USING BASELINE.FACT_FAKTURERINGSGRUNDLAG_V S
ON S.RÆKKE_ID=T.RÆKKE_ID

/*
UPDATE del udkonteret, da bogførte rækker ikke ændret sig. Endvidere tog proceduren ½-1 time af afvikle
WHEN MATCHED THEN UPDATE SET 
T.FAKTURA_LOBENUMMER=S.FAKTURA_LOBENUMMER,
T.FAKTURA_NR=S.BOGFØRT_FAKTURA_NR,
T.BOGFØRINGSDATO=S.BOGFØRINGSDATO,
T.REGNSKABSDATO=S.REGNSKABSSDATO,
T.BETALINGSFRIST=S.BETALINGSFRIST,
T.KUNDE_ID=S.KUNDE_ID,
T.[DESCRIPTION]=S.[DESCRIPTION],
T.RESSOURCEGROUP_ID=S.RESSOURCEGROUP_ID,
T.LINJE_RABAT=S.LINJE_RABAT,
T.ANTAL_ENHEDER=S.ANTAL_ENHEDER,
T.ENHEDSPRIS=S.ENHEDSPRIS,
T.LOAD_DATO=S.LOAD_DATO, 
T.BELØB_EKSKL_MOMS=S.BELØB_EKSKL_MOMS
*/
WHEN NOT MATCHED 
THEN INSERT 
(
RÆKKE_ID,
FAKTURA_LOBENUMMER,
FAKTURA_NR,
BOGFØRINGSDATO,
BETALINGSFRIST,
KUNDE_ID,
BESKRIVELSE,
RESSOURCEGROUP_ID,
LINJE_RABAT,
ANTAL_ENHEDER,
ENHEDSPRIS,
BELØB_EKSKL_MOMS,
LOAD_DATO
)
VALUES 
(
S.RÆKKE_ID,
S.FAKTURA_LOBENUMMER,
S.FAKTURA_NR,
S.BOGFØRINGSDATO,
S.BETALINGSFRIST,
S.KUNDE_ID,
BESKRIVELSE,
S.RESSOURCEGROUP_ID,
S.LINJE_RABAT,
S.ANTAL_ENHEDER,
S.ENHEDSPRIS,
S.BELØB_EKSKL_MOMS,
S.LOAD_DATO
)
WHEN NOT MATCHED BY SOURCE 
THEN DELETE
;
END;



