ALTER PROCEDURE [REPORTING].[MERGE_FACT_TURNOVER_TOTAL]
AS
BEGIN
IF OBJECT_ID('REPORTING.FACT_TURNOVER_TOTAL', 'U') IS NOT NULL 

PRINT ('MERGE_FACT_TURNOVER_TOTAL');

MERGE [REPORTING].[FACT_TURNOVER_TOTAL] T
--THE PURPOSE IS TO GENERATE A TABLE WITH TOTAL TURNOVER (REALIZED VALUE AND RUNNING SUM) AND THE BUDGET (TARGET PER MONTH AND RUNNING SUM) FOR POWER BI REPORTING
USING
	(
	SELECT B.DATE_ID, B.FISCALYEARTEXT, B.BUDGET_MONTH, B.BUDGET_RUNNING_SUM, T.TURNOVER_MONTH, T.TURNOVER_RUNNING_SUM
	FROM BASELINE.TURNOVER_BUDGET_V B
	LEFT JOIN REPORTING.TURNOVER_TOTAL_V T ON B.DATE_ID=T.DATE_ID
	) S
ON S.DATE_ID=T.DATE_ID

WHEN MATCHED THEN UPDATE SET 
T.BUDGET_MONTH=S.BUDGET_MONTH,
T.BUDGET_RUNNING_SUM=S.BUDGET_MONTH,
T.TURNOVER_MONTH=S.TURNOVER_MONTH,
T.TURNOVER_RUNNING_SUM=S.TURNOVER_RUNNING_SUM

WHEN NOT MATCHED 
THEN INSERT
(DATE_ID, BUDGET_MONTH, BUDGET_RUNNING_SUM, TURNOVER_MONTH, TURNOVER_RUNNING_SUM)
VALUES 
(DATE_ID, BUDGET_MONTH, BUDGET_RUNNING_SUM, TURNOVER_MONTH, TURNOVER_RUNNING_SUM)
;
END;
