ALTER PROCEDURE [REPORTING].[MERGE_FACT_MOBIL_DATAFORBRUG_DETAIL]
--THE PURPOSE OF THIS PROCEDURE IS TO BUILD A FACT JOINED WITH DIMENSIONS FOR REPORTING PURPOSES
--THE GRANUALITY IS SUBSCRIPTION PER MONTH AND THE MAIN FACTS IS DOWN- AND UPLOAD OF DATA 
--THE SQL STARTS WITH CURRENT AND OLD SUBSTRIPTIONS IN BASELINE.MOBIL_ABONNOMENT_V TO INCLUDE SUBSCRIPTIONS WITHOUT DATA CONSUMPTION
AS
BEGIN
IF OBJECT_ID('REPORTING.FACT_MOBIL_DATAFORBRUG_DETAIL', 'U') IS NOT NULL 

MERGE INTO REPORTING.FACT_MOBIL_DATAFORBRUG_DETAIL AS T
    USING
	(
	SELECT 
	--MEASURES
	SUM(S.VOLUME_GB) AS VOLUME_GB, 
	SUM(S.COST) AS COST, 
	--DIMENSION-ID AND ATTRIBUTES
	S.LAST_DAY_OF_MONTH_DT AS DATE_ID,
	A.ABN_ID AS ABONNEMENT_ID, 
	A.CUST AS KUNDE_ID,
	S.INVOICEGROUP_ID,
	P.PRODUCT_ID AS PRODUKT_ID
	
	FROM BASELINE.MOBIL_ABONNOMENT_V A
	LEFT JOIN RADIUS.MOB_DATA_SUMMARIZED S ON A.ABN_ID=S.ABN_ID
	LEFT JOIN RATING.MOB_ABN R ON A.ABN=R.ID
	LEFT JOIN REPORTING.DIM_PRODUKT P ON R.ID=P.ABN_ID
	
	--GROUP BY NEEDED TO AGGREGRETE ACROSSE OPERATOR_ID IN SOURCE RADIUS.MOB_DATA_SUMMARIZED
	GROUP BY 
	
	S.LAST_DAY_OF_MONTH_DT,
	A.ABN_ID, 
	A.CUST,
	S.INVOICEGROUP_ID,
	P.PRODUCT_ID 	
	
	) AS S
    
	ON 
	--THREE REFERECES TO DIMENSIONS THAT EQUALS THE UK CONSTRAIN ON THE TARGET TABEL
    (T.DATE_ID=S.DATE_ID AND T.ABONNEMENT_ID=S.ABONNEMENT_ID AND T.INVOICEGROUP_ID=S.INVOICEGROUP_ID)
		
WHEN MATCHED THEN 
   UPDATE SET 
   	T.KUNDE_ID=S.KUNDE_ID,
	T.INVOICEGROUP_ID=S.INVOICEGROUP_ID,
	T.PRODUKT_ID=S.PRODUKT_ID,
	T.VOLUME_GB=S.VOLUME_GB,
	T.COST=S.COST
		
WHEN NOT MATCHED THEN 
   INSERT VALUES
(
S.DATE_ID,
S.ABONNEMENT_ID,
S.KUNDE_ID,
S.INVOICEGROUP_ID,
S.PRODUKT_ID,
S.VOLUME_GB,
S.COST
)
;
END
