CREATE PROCEDURE [REPORTING].[MERGE_FACT_KPI_CHURN]
AS 
BEGIN
IF OBJECT_ID('REPORTING.FACT_KPI', 'U') IS NOT NULL 

PRINT 'UPDATES THE KPI "CHURN PCT" IN REPORTING.FACT_KPI';

MERGE REPORTING.FACT_KPI T
	USING 
	(
	SELECT CHURN_PCT AS REALISERET, PARTNER_ID AS FORHANDLER_ID, LAST_DAY_OF_MONTH AS DATE_ID, 78 AS KPI_ID
	FROM BASELINE.CHURN_PER_PARTNER
	WHERE LAST_DAY_OF_MONTH IN (SELECT LASTDAYOFMONTH FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK)
	) S
	
	ON (S.FORHANDLER_ID=T.FORHANDLER_ID AND S.DATE_ID=T.DATE_ID AND S.KPI_ID=T.KPI_ID)

WHEN MATCHED 
	THEN UPDATE SET 
		T.REALISERET = S.REALISERET 

WHEN NOT MATCHED 
	THEN INSERT (REALISERET, FORHANDLER_ID, DATE_ID, KPI_ID)
	VALUES (S.REALISERET, S.FORHANDLER_ID, S.DATE_ID, S.KPI_ID);

END;
