CREATE PROCEDURE [REPORTING].[SIMPEL_LOOP_INSERT]
AS 
BEGIN 

DECLARE @ROWCNT TINYINT=1;
DECLARE @MAXROW TINYINT=(SELECT MAX(ROWNO) FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK);
DECLARE @DATE_ID DATE;

WHILE @ROWCNT <= @MAXROW
	BEGIN
		
		
		SET @DATE_ID=(SELECT LASTDAYOFMONTH FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK T WHERE @ROWCNT=T.ROWNO);
		PRINT @ROWCNT 
		PRINT @DATE_ID
		
		INSERT INTO REPORTING.TEST_LOOP (RK_NR, DATO)
		VALUES (@ROWCNT, @DATE_ID);

		SET @ROWCNT = @ROWCNT + 1

	END;
	
END;

GO

