ALTER PROCEDURE [REPORTING].[TRUNC_INSERT_BEHOLDNING_ABN_MND]
AS

DROP TABLE REPORTING.BEHOLDNING_ABN_MND;

--CHR. 27.9.2021 THE UNCERTAINTY IN THE NUMBERS IS THAT THE CURRENT SUBSCRIPTION TYPE (FX DK-STOR) IS SHOWN
--THE CUSTOMERS CAN CHANGE SUBSCRIPTION OVER TIME IS SEEN ONLY ON CURRENT AND PREVIOUS YEARS.
SELECT I.ABONNOMENT, I.ÅR, I.MÅNED, I.DATO, 
CAST (I.ANTAL_ABONNOMENTER AS NUMERIC) AS ANTAL_ABONNOMENTER, 
CAST (I.NETTO_VAEKST_N AS NUMERIC) AS NETTO_VAEKST,
ROUND (CAST (I.NETTO_VAEKST_N AS NUMERIC)/CAST (I.ANTAL_ABONNOMENTER AS NUMERIC)*100,0) AS NETTO_VAEKST_PCT

INTO REPORTING.BEHOLDNING_ABN_MND

FROM 
--WRAPPED TO AVOID CONVERTING TO DECIMAL AND CALCULATING ANALYTICAL EXP AGAIN
(
	SELECT 
	V.ABN_NAVN AS ABONNOMENT, 
	YEAR(V.DATE_ID) AS ÅR, 
	MONTH(V.DATE_ID) AS MÅNED,
	V.DATE_ID AS DATO,
	COUNT(DISTINCT V.ABN_ID) AS ANTAL_ABONNOMENTER, 
	(COUNT(DISTINCT V.ABN_ID)-LAG (COUNT(DISTINCT V.ABN_ID)) OVER (PARTITION BY V.ABN_NAVN ORDER BY YEAR(DATE_ID), MONTH(V.DATE_ID) ASC))  AS NETTO_VAEKST_N
	-- THE SOURCE VIEW CONSISTES OF A UNION OF ADMIN.MOBIL_ABN (ACTIVE CELLUAR SUBSCRIPTIONS) AND ADMIN.MOBIL_ABN_OLD (DEACTIVE CELLUAR SUBSCRIPTIONS) CROSSJOINET WITH ALL THE MONTHS OF THE CURRENT AND PREVIOUS YEARS
	FROM BASELINE.MOBIL_ABONNOMENTER_PR_MND_V V
	WHERE YEAR(DATE_ID)>=YEAR(GETDATE())-1 
	AND DATE_ID<=GETDATE()
	GROUP BY V.ABN_NAVN, DATE_ID, YEAR(DATE_ID), MONTH(DATE_ID)
) I
;

