CREATE PROCEDURE [REPORTING].[UPDATE_DIM_INVOICEGROUP]
--CHO 20.4.2021 TARGET (DIMENSIONEN) TRUNKES FOR AT VÆRE SIKKER PÅ DATA ER OPDATEREDE I TARGET
--CHO 20.4.2021 TRUNCATE ERSTATTET MED MERGE FOR AT SIKRE STABILE DATASÆT I REPORTING OGSÅ HVIS KILDELOAD FEJLER
--CHO 17.6.2021 -1 VÆRDI TILFØJET
--CHO 8.7.2021 Kolonnenavn invoicegroupname ændret til invoicegroup_name i target
AS
BEGIN
IF OBJECT_ID('REPORTING.DIM_INVOICEGROUP', 'U') IS NOT NULL 

MERGE INTO REPORTING.DIM_INVOICEGROUP AS T
    USING
	(	
		SELECT 
		INVOICEGROUP_ID, INVOICEGROUP_NAME, SYSTEM, DATA, EVENT, LOAD_DATO
 		FROM BASELINE.INVOICEGROUP_V 
		UNION 
		SELECT -1, 'Ukendt/Blank', null, null, null, getdate()
	)
	AS S
    ON T.INVOICEGROUP_ID= S.INVOICEGROUP_ID

WHEN MATCHED THEN 
   UPDATE SET 
   T.INVOICEGROUP_NAME=S.INVOICEGROUP_NAME,
   T.[SYSTEM]=S.[SYSTEM],
   T.[DATA]=S.[DATA],
   T.[EVENT]=S.[EVENT],
   T.LOAD_DATO=S.LOAD_DATO

WHEN NOT MATCHED THEN 
INSERT VALUES
(
S.INVOICEGROUP_ID,
S.INVOICEGROUP_NAME,
S.SYSTEM,
S.DATA,
S.EVENT,
S.LOAD_DATO
);

END;

GO

