CREATE PROCEDURE [REPORTING].[UPDATE_FACT_KPI_HPBX_MOBIL_BRUGERE]
AS 
BEGIN
IF OBJECT_ID('REPORTING.FACT_KPI', 'U') IS NOT NULL 

PRINT 'OPDATERER KPI "HOSTEDPBX MOBIL BRUGERE" I REPORTING.FACT_KPI';

MERGE REPORTING.FACT_KPI T
	USING 
	(
	SELECT 
	SUM(MOBIL) AS REALISERET,
	EXTERNAL_PARTNER_ID AS FORHANDLER_ID,
	DATO AS DATE_ID,
	(SELECT KPI_ID FROM REPORTING.DIM_KPI WHERE KPI_NAVN='HostedPBX Mobilbrugere') AS KPI_ID	

	FROM BASELINE.HPBX_STATS 
	
	WHERE DATO IN (SELECT LASTDAYOFMONTH FROM BASELINE.LASTDAYOFMONTH_ONE_YEAR_BACK)
	--DER MERGES KUN DATA FOR SIDSTE DAG I HVER MÅNED I INDEVÆRENDE OG SIDSTE ÅR		
	
	GROUP BY EXTERNAL_PARTNER_ID, DATO	
	--DER SUMMES OG GRUPPERES, DA ENKELTE FORHANDLERE HAR KUNDER I HVER SIN ONE CONNECT DB
	) S
	
	ON (S.FORHANDLER_ID=T.FORHANDLER_ID AND S.DATE_ID=T.DATE_ID AND S.KPI_ID=T.KPI_ID)

WHEN MATCHED 
	THEN UPDATE SET 
		T.REALISERET = S.REALISERET 

WHEN NOT MATCHED 
	THEN INSERT (REALISERET, FORHANDLER_ID, DATE_ID, KPI_ID)
	VALUES (S.REALISERET, S.FORHANDLER_ID, S.DATE_ID, S.KPI_ID);
	
END;

GO

