CREATE PROCEDURE [REPORTING].[UPDATE_DIM_MOBIL_ABONNEMENT]
--CHO 21-04-2021 TARGET TABEL OPRETTES I SEPERAT SCRIPT FOR AT KUNNE HÅNDTERE DATATYPER OG CONSTRAINTS EKSPLICIT. 
--CHO 21-04-2021 UPDATE FOR AT SIKRE REPORTING SOM ET KONSISTENT LAG OGSÅ, HVIS LOAD AF KILDEDATA FEJLER 
AS
BEGIN
IF OBJECT_ID('REPORTING.DIM_MOBIL_ABONNEMENT', 'U') IS NOT NULL 

MERGE INTO REPORTING.DIM_MOBIL_ABONNEMENT AS T
    USING(SELECT * FROM BASELINE.MOBIL_ABONNOMENT_V) AS S
    ON T.ABONNEMENT_ID= S.ABN_ID
WHEN MATCHED THEN 
   UPDATE SET 
    T.CUST=S.CUST,
    T.COUNTRY_ID=S.COUNTRY_ID,
    T.MOBIL_NR=S.MOBIL_NR,
    T.NAVN=S.NAVN,
    T.EXTRA=S.EXTRA,
    T.ABN=S.ABN,
    T.STARTDATE=S.STARTDATE,
    T.ENDDATE=S.ENDDATE,
    T.ICC=S.ICC,
    T.SUSPENDED=S.SUSPENDED,
    T.IMSI=S.IMSI,
    T.NUMBERTYPE=S.NUMBERTYPE,
    T.ICCTYPE=S.ICCTYPE,
	T.OPERATOR_ID=S.OPERATOR_ID,
    T.STATUS_ID=S.STATUS_ID,
    T.STATUS_NAVN=S.STATUS_NAVN
   
WHEN NOT MATCHED THEN 
   INSERT VALUES
    (
    S.ABN_ID,
    S.CUST,
    S.COUNTRY_ID,
    S.MOBIL_NR,
    S.NAVN,
    S.EXTRA,
    S.ABN,
    S.STARTDATE,
    S.ENDDATE,
    S.ICC,
    S.SUSPENDED,
    S.IMSI,
    S.NUMBERTYPE,
    S.ICCTYPE,
	S.OPERATOR_ID,
    S.STATUS_ID,
    S.STATUS_NAVN
    );

-- Værdien -1 svarende til ukendt/blank (null) indsættes
IF (SELECT ABONNEMENT_ID FROM REPORTING.DIM_MOBIL_ABONNEMENT WHERE ABONNEMENT_ID=-1) IS NULL 
INSERT INTO REPORTING.DIM_MOBIL_ABONNEMENT (ABONNEMENT_ID)
VALUES (-1)

END;

GO

