CREATE PROCEDURE [REPORTING].[UPDATE_DIM_RESSOURCEGROUP]
AS
BEGIN

DECLARE

	@ERRORMESSAGE VARCHAR(MAX),
	@ERRORSEVERITY VARCHAR(MAX),
	@ERRORSTATE VARCHAR(MAX);

BEGIN TRY 

	IF OBJECT_ID('REPORTING.DIM_RESSOURCEGROUP', 'U') IS NOT NULL 

	PRINT ('Merge operation')

	MERGE INTO REPORTING.DIM_RESSOURCEGROUP AS T
		USING
		(
		SELECT 
		-1 AS RESSOURCEGROUP_ID,
		'Ukendt/Blank' AS RESSOURCEGROUP_NAVN, 
		NULL  AS RESSOURCEGROUP_TYPE, 
		'Ukendt/Blank' AS BASISENHED, 
		0 AS ENHEDSPRIS, 
		'Ukendt/Blank' AS PRODUKTBOGFØRINGSGRUPPE
	
		UNION 

	SELECT 
		[NO_] AS RESSOURCEGROUP_ID,
		[NAME] AS RESSOUCEGROUP_NAVN,
		[TYPE] AS RESSOURCEGROUP_TYPE,
		[BASE UNIT OF MEASURE] AS BASISENHED,
		[UNIT PRICE] AS ENHEDSPRIS,
		[GEN_ PROD_ POSTING GROUP] AS PRODUKTBOGFØRINGSGRUPPE
	
		FROM [NAVISION].[UNI-TEL_AS_RESOURCE]
		) AS S

		ON T.RESSOURCEGROUP_ID=S.RESSOURCEGROUP_ID

	WHEN MATCHED THEN 
	   UPDATE SET 
		T.RESSOURCEGROUP_NAVN=S.RESSOURCEGROUP_NAVN,
		T.RESSOURCEGROUP_TYPE=S.RESSOURCEGROUP_TYPE,
		T.BASISENHED=S.BASISENHED,
		T.ENHEDSPRIS=S.ENHEDSPRIS,
		T.PRODUKTBOGFØRINGSGRUPPE=S.PRODUKTBOGFØRINGSGRUPPE
   
	WHEN NOT MATCHED THEN 
	   INSERT VALUES
	   (S.RESSOURCEGROUP_ID,
		S.RESSOURCEGROUP_NAVN,
		S.RESSOURCEGROUP_TYPE,
		S.BASISENHED,
		S.ENHEDSPRIS,
		S.PRODUKTBOGFØRINGSGRUPPE); 

END TRY

BEGIN CATCH
	SET @ERRORMESSAGE  = ERROR_MESSAGE()
    SET @ERRORSEVERITY = ERROR_SEVERITY()
    SET @ERRORSTATE    = ERROR_STATE()
    RAISERROR(@ERRORMESSAGE, @ERRORSEVERITY, @ERRORSTATE)

END CATCH 

END;

GO

