CREATE  PROCEDURE [REPORTING].[UPDATE_DIM_TRUNK]
AS
BEGIN

IF OBJECT_ID('REPORTING.DIM_TRUNK', 'U') IS NOT NULL 

MERGE INTO REPORTING.DIM_TRUNK AS T
    USING(SELECT * FROM BASELINE.TRUNK_V) AS S
    ON T.TRUNK_ID= S.USERNAME
WHEN MATCHED THEN 
   UPDATE SET 
	T.TRUNK_ID=S.USERNAME,
	T.KUNDE_ID=S.CUST,
	T.KAPACITET=S.CAPACITY,
	T.SIPPLATFORM=S.SIPPLATFORM,
	T.STARTDATO=S.CREATED,
	T.SLUTDATO=S.ENDDATE,
	T.TRUNKTYPE=S.TRUNKTYPE,
	T.SIPPLATFORM_NAVN=S.SIPPLATFORM_NAVN,
	T.LOAD_DATO=S.LOAD_DATO
	
WHEN NOT MATCHED THEN 
   INSERT VALUES
   (S.USERNAME,
	S.CUST,
	S.CAPACITY,
	S.SIPPLATFORM,
	S.CREATED,
	S.ENDDATE, 
	S.TRUNKTYPE,
	S.AKTIV,
	S.TRUNKTYPE,
	S.SIPPLATFORM_NAVN,
	S.LOAD_DATO)
	
WHEN NOT MATCHED BY SOURCE THEN DELETE
;

PRINT 'Værdien -1 svarende til ukendt/blank (null) indsættes, hvis den ikke findes'
IF (SELECT TRUNK_ID FROM REPORTING.DIM_TRUNK WHERE TRUNK_ID=-1) IS NULL 
INSERT INTO REPORTING.DIM_TRUNK (TRUNK_ID)
VALUES (-1)

END;
