CREATE VIEW [ANALYSER].[DATADOWNLOAD_V]
AS
(
SELECT ROUND(SUM(volume_GB)/COUNT(DISTINCT ABN_ID),1) AS TRAFIK_GB_GNM, 	
COUNT(DISTINCT ABN_ID) AS DISTINKTE_ABN, 	
I.ABN_NAME,	
I.ÅR, 	
I.MÅNED	
FROM 	
(	
--25.08.2021 SQL TAGER NU UDGANGSPUNKT ABN DER NU ER AKTIVE OG REGNER GENNEMSNIT PÅ DISSE ABONNENETERS FORBRUG PÅ I HISTORISKE PERIODER
--PRINCIPPET ER VALGT FOR AT KUNNE OPGØRE ANTAL SKUFFEMOBILER, SOM GIVER FORNUFTIGE INDTÆGTER
--PRINCIPPET SORTERER DOG NOGLE ABN FRA SOM VAR AKTIV I HISTORISKE PERIODER. VI MANGLER HISTORISKE DATA TIL AT GØRE DETTE ME
SELECT SUM(VOLUME_GB) AS VOLUME_GB, A.ID AS ABN_ID, R.ABNNAME AS ABN_NAME, YEAR(S.LAST_DAY_OF_MONTH_DT) AS ÅR, MONTH(S.LAST_DAY_OF_MONTH_DT) AS MÅNED	
from ADMIN.MOBIL_ABN a
LEFT JOIN RADIUS.MOB_DATA_SUMMARIZED S ON S.ABN_ID=A.ID	
LEFT JOIN RATING.MOB_ABN R ON A.ABN=R.ID	
WHERE YEAR(S.LAST_DAY_OF_MONTH_DT) IN (2019, 2021,2020)	
--DE 4 ØNSKEDE EU PREMIUM ABN 100, 50, 5 OG MINI	
AND R.ABNNAME LIKE '%EU%' AND R.ACTIVE=1 	
AND A.STATUS IN (3) --KUN AKTIVE ABN MEDTAGET, DA VI IKKE VED I HVILKEN PERIODE ABN X HAVDE EN BESTEMT STATUS
 --GRUPPERING PR. ABONOMMENT ID OG TID	
GROUP BY A.ID, R.ABNNAME, YEAR(S.LAST_DAY_OF_MONTH_DT), MONTH(S.LAST_DAY_OF_MONTH_DT)  	
--KUN ABN MED DOWNLOAD AF MINDST 0,5 GB MEDTAGET FOR AT FRASORTERE SKUFFE MOBILER 
HAVING SUM(VOLUME_GB)>0.5 
) I	
GROUP BY I.ABN_NAME, I.ÅR, I.MÅNED
--ORDER BY I.ABN_NAME, I.ÅR, I.MÅNED
)

GO

