CREATE VIEW [ANALYSER].[OPKALD_MED_LAENGDE_V]
AS
(
SELECT 	
I.YEAR AS ÅR, 	
I.MONTH AS MÅNED,
I.ABNNAME,	
COUNT(DISTINCT ABN_ID) AS DISTINKTE_ABN,	
ROUND(SUM(I.ANTAL_UDGAAENDE_OPKALD)/COUNT(DISTINCT ABN_ID),1) AS GNM_ANTAL_OPKALD,	
ROUND(SUM(I.OPKALDS_VARIHED_TIMER)/COUNT(DISTINCT ABN_ID),1) AS GNM_TALETID_TIMER
FROM 
	(
	--SQL TAGER NU UDGANGSPUNKT ABN DER NU ER AKTIVE OG REGNER GENNEMSNIT PÅ DISSE ABONNENETERS FORBRUG PÅ I HISTORISKE PERIODER
	--PRINCIPPET ER VALGT FOR AT KUNNE OPGØRE ANTAL SKUFFEMOBILER, SOM GIVER FORNUFTIGE INDTÆGTER
	--PRINCIPPET SORTERER DOG NOGLE ABN FRA SOM VAR AKTIV I HISTORISKE PERIODER. VI MANGLER HISTORISKE DATA TIL AT GØRE DETTE MERE PRÆCIST
	SELECT SUM(ANTAL_UDGAAENDE_OPKALD) AS ANTAL_UDGAAENDE_OPKALD, ROUND((SUM (S.DUR)/60/60),1) AS OPKALDS_VARIHED_TIMER, A.ID AS ABN_ID, R.ABNNAME, YEAR(S.LAST_DAY_OF_MONTH_DT) AS YEAR, MONTH(S.LAST_DAY_OF_MONTH_DT) AS MONTH
	FROM ADMIN.MOBIL_ABN A 
	LEFT JOIN RADIUS.MOB_CDR_SUMMARIZED S ON S.MOB_CUST=A.ID
	LEFT JOIN RATING.MOB_ABN R ON R.ID=A.ABN
	WHERE YEAR(S.LAST_DAY_OF_MONTH_DT) IN (2019, 2020, 2021)
	--DE 4 ØNSKEDE EU PREMIUM ABN 100, 50, 5 OG MINI
	AND R.ABNNAME LIKE '%EU%' AND R.ACTIVE=1 
	AND A.STATUS IN (3) --KUN AKTIVE ABN MEDTAGET, DA VI IKKE VED I HVILKEN PERIODE ABN X HAVDE EN BESTEMT STATUS

	--GRUPPERING PR. ABONOMMENT ID OG TID
	GROUP BY A.ID, R.ABNNAME, YEAR(S.LAST_DAY_OF_MONTH_DT), MONTH(S.LAST_DAY_OF_MONTH_DT)
	--KUN ABN MED MINDST 6 OPKALD MEDTAGET 
	HAVING SUM(ANTAL_UDGAAENDE_OPKALD)>5  --SORTERER SKUFFEMOBILE FRA 
	--HAVING SUM(ANTAL_UDGAAENDE_OPKALD)<=5 --SKUFFEMOBILER
	) I
GROUP BY ABNNAME, YEAR, MONTH
)

GO

